language: php

sudo: false

php:
    - 7.1
    - 7.2

cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - composer install

script:
    - ./vendor/bin/phpunit
    - ./vendor/bin/phpstan analyse --level7 lib
